Repository metoop/Dynamic-programming, pull requests merged in 2020-10, with the labels that each got.

#3 tsp added dp with bitmask
  tsp.cpp
Labels: done, hacktoberfest-accepted

#4 edit distance added in c++
  editDistance.cpp
Labels: Dynamic-programming, done, hacktoberfest-accepted

#10 matrixChainMultiplication
  MatrixChainMultiplication/MatrixChainMultiplication_Class.java
  MatrixChainMultiplication/driver.java
  MatrixChainMultiplication_Input.txt
Labels: hacktoberfest-accepted

#12 knapsack.cpp added
  Knapsack.cpp
Labels: done, hacktoberfest-accepted

#13 LCS.cpp added
  LCS.cpp
Labels: done, hacktoberfest-accepted

#14 LPS.cpp added
  LPS.cpp
Labels: hacktoberfest-accepted

#17 Added Longest Path Solution
  Longest_Path.cpp
Labels: hacktoberfest-accepted

#19 Create Ugly.cpp
  Ugly.cpp
Labels: C++, done, hacktoberfest-accepted
